version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    image: seedcase-registry
    container_name: seedcase-registry
    command: python manage.py runserver 0.0.0.0:8080
    healthcheck:
      test: curl --fail http://localhost:8080 || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
    env_file:
      - .env.django
    volumes:
      - .:/home/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always
  db:
    image: postgres:13-alpine
    container_name: registry_db
    env_file:
      - .env.django
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
