# Generated by Django 4.1.2 on 2023-08-09 12:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base_app", "0002_request"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="variable",
            name="project",
        ),
    ]
